### PR TITLE
Split image h3s

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
This is the results of running `./manage.py runscript dehtmlify` with the code in https://github.com/mozilla/masterfirefoxos/pull/136 and should not be merged until after the db modifications in that script have been made.

**Comment by glogiotatidis** [comment]
Unfortunately this needs a rebase

**Comment by jgmize** [comment]
@glogiotatidis I've updated this PR with a new run of `./manage.py runscript dehtmilify` using the code from https://github.com/jgmize/masterfirefoxos/commit/f7717f8d4c98bde2917bcdc80b8ddef5f3b41053 against the latest master of this repo.

**Comment by jgmize** [comment]
ran the new `dehtmlify` in prod; this can now be merged.

**Pull request merged**
