### PR TITLE
Add ja

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@bensternthal r?

**Comment by bensternthal** [comment]
@jgmize this po file appears to have strings from 1.1, 1.3 and 2.0 (as do all the others).

Unless I am missing something they should only contain strings that match what they are assigned in our settings file. This way localizers will only translate what is necessary.

For example we know japanese only needs 2.0 there is no need to translate 1.1 and 1.3.

**Comment by jgmize** [comment]
@bensternthal I'm not aware of a way to restrict the strings that appear in the file, but we do comment the PO file with the page path, and we can tell the localizers that they don't need to worry about translating strings from the older versions.

**Comment by bensternthal** [comment]
I understand this is how it needs to work but I can see this being confusing to localizers.

When someone goes to pontoon.. they are just going to localize everything. We can communicate via peying but that wont prevent someone from the community who is not in the loop from translating unnecessary strings.

**Pull request merged**
